name: Package plugin on source changes
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: karolpiczak-forks/obsidian-plugins/.github/workflows/build-release.yml@main
    permissions:
      contents: write
    with:
      dist_files: |
        manifest.json
        main.js
